import { Resend } from 'resend'
import { Document, Profile } from '../supabase/types'
import { formatCurrency, formatDate, generateViewUrl } from '../utils/formatters'

const resend = new Resend(process.env.RESEND_API_KEY!)

type ReminderType = 'reminder_3' | 'reminder_7' | 'reminder_14'

const reminderMessages: Record<ReminderType, { subject: (doc: Document) => string; intro: string; urgency: string; color: string }> = {
  reminder_3: {
      subject: (doc) => `Rappel de paiement - Facture ${doc.number}`,
          intro: 'Nous vous contactons pour vous rappeler que votre facture arrive bientôt à échéance.',
              urgency: 'Rappel amical',
                  color: '#F59E0B',
                    },
                      reminder_7: {
                          subject: (doc) => `Relance de paiement - Facture ${doc.number} (7 jours de retard)`,
                              intro: 'Nous n\'avons pas encore reçu le règlement de votre facture qui est arrivée à échéance il y a 7 jours.',
                                  urgency: 'Première relance',
                                      color: '#F97316',
                                        },
                                          reminder_14: {
                                              subject: (doc) => `URGENT - Facture ${doc.number} en souffrance (14 jours de retard)`,
                                                  intro: 'Malgré nos précédentes relances, le règlement de votre facture n\'a toujours pas été effectué. Cette facture accuse un retard de 14 jours.',
                                                      urgency: 'Deuxième relance urgente',
                                                          color: '#EF4444',
                                                            },
                                                            }

                                                            export async function sendReminderEmail(
                                                              document: Document,
                                                                profile: Profile,
                                                                  recipientEmail: string,
                                                                    recipientName: string,
                                                                      reminderType: ReminderType
                                                                      ): Promise<string> {
                                                                        const reminder = reminderMessages[reminderType]
                                                                          const viewUrl = generateViewUrl(document.view_token)
                                                                            const companyName = profile.company_name || profile.full_name || 'Votre prestataire'
                                                                              const subject = reminder.subject(document)

                                                                                const html = `
                                                                                <!DOCTYPE html>
                                                                                <html lang="fr">
                                                                                <head>
                                                                                  <meta charset="UTF-8">
                                                                                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                                                                                      <title>${subject}</title>
                                                                                        <style>
                                                                                            body { font-family: 'Helvetica Neue', Arial, sans-serif; margin: 0; padding: 0; background: #f5f5f5; color: #333; }
                                                                                                .container { max-width: 600px; margin: 0 auto; background: #fff; }
                                                                                                    .header { background: ${reminder.color}; padding: 24px 40px; }
                                                                                                        .header h1 { color: #fff; margin: 0; font-size: 20px; font-weight: 700; }
                                                                                                            .header .badge { display: inline-block; background: rgba(0,0,0,0.2); color: #fff; padding: 4px 12px; border-radius: 100px; font-size: 12px; margin-top: 8px; }
                                                                                                                .body { padding: 40px; }
                                                                                                                    .doc-card { background: #fef2f2; border: 1px solid #fecaca; border-radius: 8px; padding: 24px; margin: 24px 0; }
                                                                                                                        .doc-detail { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #fee2e2; }
                                                                                                                            .doc-detail:last-child { border-bottom: none; }
                                                                                                                                .doc-detail .label { color: #6b7280; font-size: 14px; }
                                                                                                                                    .doc-detail .value { font-weight: 600; font-size: 14px; }
                                                                                                                                        .total-amount { font-size: 28px; font-weight: 700; color: ${reminder.color}; text-align: center; padding: 16px; }
                                                                                                                                            .btn { display: inline-block; padding: 14px 28px; border-radius: 8px; text-decoration: none; font-weight: 600; font-size: 15px; margin: 8px 0; }
                                                                                                                                                .btn-pay { background: #10B981; color: #fff; }
                                                                                                                                                    .btn-view { background: #1A56DB; color: #fff; margin-left: 12px; }
                                                                                                                                                        .footer { background: #f9fafb; padding: 24px 40px; border-top: 1px solid #e5e7eb; text-align: center; }
                                                                                                                                                            .footer p { color: #9ca3af; font-size: 12px; margin: 4px 0; }
                                                                                                                                                              </style>
                                                                                                                                                              </head>
                                                                                                                                                              <body>
                                                                                                                                                                <div class="container">
                                                                                                                                                                    <div class="header">
                                                                                                                                                                          <h1>${companyName}</h1>
                                                                                                                                                                                <div class="badge">${reminder.urgency}</div>
                                                                                                                                                                                    </div>
                                                                                                                                                                                        <div class="body">
                                                                                                                                                                                              <p>Bonjour ${recipientName},</p>
                                                                                                                                                                                                    <p>${reminder.intro}</p>
                                                                                                                                                                                                          
                                                                                                                                                                                                                <div class="doc-card">
                                                                                                                                                                                                                        <div class="doc-detail">
                                                                                                                                                                                                                                  <span class="label">Numéro de facture</span>
                                                                                                                                                                                                                                            <span class="value">${document.number}</span>
                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                            <div class="doc-detail">
                                                                                                                                                                                                                                                                      <span class="label">Date d'émission</span>
                                                                                                                                                                                                                                                                                <span class="value">${formatDate(document.issue_date)}</span>
                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                ${document.due_date ? `<div class="doc-detail"><span class="label">Date d'échéance</span><span class="value" style="color: ${reminder.color};">${formatDate(document.due_date)}</span></div>` : ''}
                                                                                                                                                                                                                                                                                                        <div class="total-amount">${formatCurrency(document.total)} TTC</div>
                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                          <p>Pour procéder au règlement ou consulter le détail de la facture, veuillez cliquer sur les boutons ci-dessous :</p>
                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                      <div style="margin: 24px 0;">
                                                                                                                                                                                                                                                                                                                                              ${document.stripe_payment_link ? `<a href="${document.stripe_payment_link}" class="btn btn-pay">Payer en ligne</a>` : ''}
                                                                                                                                                                                                                                                                                                                                                      <a href="${viewUrl}" class="btn btn-view">Voir la facture</a>
                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                        <p style="color: #6b7280; font-size: 14px;">Si vous avez déjà effectué ce règlement, veuillez ignorer ce message et nous en informer à ${profile.company_email || 'votre adresse email'}.</p>
                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                    <p>Cordialement,<br><strong>${companyName}</strong></p>
                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                            <div class="footer">
                                                                                                                                                                                                                                                                                                                                                                                                  <p>${companyName}</p>
                                                                                                                                                                                                                                                                                                                                                                                                        ${profile.company_email ? `<p>${profile.company_email}</p>` : ''}
                                                                                                                                                                                                                                                                                                                                                                                                              ${profile.company_phone ? `<p>${profile.company_phone}</p>` : ''}
                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                    </body>
                                                                                                                                                                                                                                                                                                                                                                                                                    </html>`
                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                      const { data, error } = await resend.emails.send({
                                                                                                                                                                                                                                                                                                                                                                                                                          from: `${companyName} <noreply@facturedoc.ai>`,
                                                                                                                                                                                                                                                                                                                                                                                                                              to: recipientEmail,
                                                                                                                                                                                                                                                                                                                                                                                                                                  subject,
                                                                                                                                                                                                                                                                                                                                                                                                                                      html,
                                                                                                                                                                                                                                                                                                                                                                                                                                        })
                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                          if (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                              throw new Error(`Failed to send reminder: ${error.message}`)
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                  return data?.id || ''
                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
